### POST de Pedidos
POST http://localhost:3001/pedidos/insere HTTP/1.1
content-type: application/json

{
    "produtos" : [
        {"id_produtos": 22, "quantidade": 51 },
        {"id_produtos": 23, "quantidade": 41 }
    ],
    "observacao" : "Testando o pedido mesa 29, para o mateus poder testar",
    "mesa" : 27,
    "id_cliente" : 4
}

### PUT de Pedidos
PUT http://localhost:3001/pedidos/altera/7 HTTP/1.1
content-type: application/json

{
    "observacao" : "Testando o pedido 9, sou Alérgico",
    "mesa" : 9,
    "id_cliente" : 4,
    "status" : "aguardando"
}

### GET de Pedido pela Mesa
GET  http://localhost:3001/pedidos/busca_nao_enviado_por_mesa/27 HTTP/1.1
content-type: application/json

### GET de Pedido pelo id_pedido
GET  http://localhost:3001/pedidos/busca/7 HTTP/1.1
content-type: application/json

### GET de Pedidos Hoje
GET  http://localhost:3001/pedidos/busca_todos_hoje HTTP/1.1
content-type: application/json 

### GET de Pedidos por mesa
GET  http://localhost:3001/pedidos/busca_todos_hoje HTTP/1.1
content-type: application/json 

