### POST de Vendas
POST http://localhost:3001/vendas/insere HTTP/1.1
content-type: application/json

{
    "pedidos" : [
        {"id_pedidos": "122"}
    ],
    "total_custo": 1000.00,
    "total_venda": 1453.80,
    "forma_de_pagamento": "Cartão", 
    "observacao": "Lanche",
    "id_cliente": "1"
}